name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install xorg dependencies
      run: sudo apt-get install xorg-dev libxcb-icccm4-dev libxcb-keysyms1-dev
    - name: make
      run: make
